apiVersion: v1
kind: Service
metadata:
  name: signalfx-agent
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app=signalfx-agent
