# A Kubernetes Helm values file that you can use when deploying the agent in a
# development K8s cluster with a Splunk cluster. You should change the imageTag
# to whatever tag you are using for development.

# Disable sending to SignalFx
signalFxEnabled: false

splunkUrl: https://splunk-splunk-kube:8088/services/collector
splunkToken: 12345678-ABCD-EFGH-IJKL-123456789012
splunkSource: sfx
splunkIndex: sfx
splunkSkipTLSVerify: true

clusterName: dev-cluster

image:
  tag: 5.3.2
  pullPolicy: Always
fullnameOverride: agent


kubeletAPI:
  skipVerify: true

monitors:
  - type: docker-container-stats
    enableExtraCPUMetrics: true
  - type: prometheus-exporter
    discoveryRule: port == 8443 && container_image =~ "orderer"
    extraDimensions:
      metric_source: prometheus
      host_type: orderer
  - type: prometheus-exporter
    discoveryRule: port == 9443 && container_image =~ "peer"
    extraDimensions:
      metric_source: prometheus
      host_type: peer
  - type: prometheus-exporter
    host: hlf-orderer--orderer--orderer
    port: 8443
    extraDimensions:
      metric_source: prometheus
      host_type: orderer
  - type: prometheus-exporter
    host: hlf-orderer--orderer--orderer2
    port: 8443
    extraDimensions:
      metric_source: prometheus
      host_type: orderer
  - type: prometheus-exporter
    host: hlf-orderer--orderer--orderer3
    port: 8443
    extraDimensions:
      metric_source: prometheus
      host_type: orderer
  - type: prometheus-exporter
    host: hlf-orderer--orderer--orderer4
    port: 8443
    extraDimensions:
      metric_source: prometheus
      host_type: orderer
  - type: prometheus-exporter
    host: hlf-orderer--orderer--orderer5
    port: 8443
    extraDimensions:
      metric_source: prometheus
      host_type: orderer
  - type: prometheus-exporter
    host: hlf-peer--manufacturer--peer0
    port: 9443
    extraDimensions:
      metric_source: prometheus
      host_type: peer
  - type: prometheus-exporter
    host: hlf-peer--manufacturer--peer1
    port: 9443
    extraDimensions:
      metric_source: prometheus
      host_type: peer
  - type: prometheus-exporter
    host: hlf-peer--clearinghouse--peer0
    port: 9443
    extraDimensions:
      metric_source: prometheus
      host_type: peer
  - type: prometheus-exporter
    host: hlf-peer--clearinghouse--peer1
    port: 9443
    extraDimensions:
      metric_source: prometheus
      host_type: peer
  - type: trace-forwarder
    listenAddress: 0.0.0.0:9080
    extraSpanTags:
      environment: hyperledger-demo
  - type: prometheus-exporter
    host: ipfs-ipfs.default
    port: 5001
    metricPath: /debug/metrics/prometheus
    extraDimensions:
      metric_source: prometheus
      host_type: ipfs