---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "poc-bids"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "POC Bids"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see tradefloor.yaml and acme.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  poc-bids:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("clearinghouse" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      peer0.clearinghouse.example.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.clearinghouse.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.manufacturer.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.manufacturer.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0

#
# list of participating organizations in this network
#
organizations:
  Clearinghouse:
    mspid: ClearinghouseMSP

    peers:
      - peer0.clearinghouse.example.com
      - peer1.clearinghouse.example.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-Clearinghouse
    adminPrivateKey:
      path: /artifacts/crypto-config/peerOrganizations/clearinghouse.example.com/users/Admin@clearinghouse.example.com/msp/keystore/11597db4951044f02dc581b2da9e2065b5b322a44ceebdcd40591c47b6dc4abe_sk
    signedCert:
      path: /artifacts/crypto-config/peerOrganizations/clearinghouse.example.com/users/Admin@clearinghouse.example.com/msp/signcerts/Admin@clearinghouse.example.com-cert.pem
  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  Manufacturer:
    mspid: ManufacturerMSP
    peers:
      - peer0.manufacturer.example.com
      - peer1.manufacturer.example.com
    certificateAuthorities:
      - ca-Manufacturer
    adminPrivateKey:
      path: /artifacts/crypto-config/peerOrganizations/manufacturer.example.com/users/Admin@manufacturer.example.com/msp/keystore/390c85fbbe6e09ca9048102b0a37cc5d3c524c6da96c68848bffa52ec2945892_sk
    signedCert:
      path: /artifacts/crypto-config/peerOrganizations/manufacturer.example.com/users/Admin@manufacturer.example.com/msp/signcerts/Admin@manufacturer.example.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.example.com:
    url: grpcs://hlf-orderer--orderer:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.example.com

    tlsCACerts:
      path: /artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.clearinghouse.example.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://peer0.clearinghouse.example.com:7051

    grpcOptions:
      ssl-target-name-override: peer0.clearinghouse.example.com
    tlsCACerts:
      path: /artifacts/crypto-config/peerOrganizations/clearinghouse.example.com/peers/peer0.clearinghouse.example.com/tls/ca.crt

  peer1.clearinghouse.example.com:
    url: grpcs://hlf-peer--clearinghouse--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer1.clearinghouse.example.com
    tlsCACerts:
      path: /artifacts/crypto-config/peerOrganizations/clearinghouse.example.com/peers/peer1.clearinghouse.example.com/tls/ca.crt

  peer0.manufacturer.example.com:
    url: grpcs://hlf-peer--manufacturer--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer0.manufacturer.example.com
    tlsCACerts:
      path: /artifacts/crypto-config/peerOrganizations/manufacturer.example.com/peers/peer0.manufacturer.example.com/tls/ca.crt

  peer1.manufacturer.example.com:
    url: grpcs://hlf-peer--manufacturer--peer1:7051
    grpcOptions:
      ssl-target-name-override: peer1.manufacturer.example.com
    tlsCACerts:
      path: /artifacts/crypto-config/peerOrganizations/manufacturer.example.com/peers/peer1.manufacturer.example.com/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-Clearinghouse:
    url: https://hlf-ca--clearinghouse:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: /artifacts/crypto-config/peerOrganizations/clearinghouse.example.com/ca/ca.clearinghouse.example.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.clearinghouse.example.com

  ca-Manufacturer:
    url: https://hlf-ca--manufacturer:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /artifacts/crypto-config/peerOrganizations/manufacturer.example.com/ca/ca.manufacturer.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-Manufacturer
