apiVersion: v1
kind: Service
metadata:
  name: fabric-logger-{{ .Values.peer.peerName }}
  labels:
    app.kubernetes.io/name: {{ include "fabric-logger.name" . }}
    helm.sh/chart: {{ include "fabric-logger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    addToHostAliases: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fabric-logger.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
