# A Kubernetes Helm values file that you can use when deploying the agent in a
# development K8s cluster with a Splunk cluster. You should change the imageTag
# to whatever tag you are using for development.

clusterName: dev-cluster

image:
  repository: tmio/signalfx-demo
  tag: latest
  pullPolicy: Always
fullnameOverride: agent

kubeletAPI:
  skipVerify: true

agentConfig:
  signalFxAccessToken: ${SFX_ACCESS_TOKEN}

  signalFxRealm: us0

  disableHostDimensions: false

  etcPath: /hostfs/etc
  procPath: /hostfs/proc

  enableBuiltInFiltering: true

  intervalSeconds: 10

  cluster: dev-cluster

  writer:
    signalFxEnabled: true
    splunk:
      enabled: true
      url: https://splunk-splunk-kube:8088/services/collector
      token: 12345678-ABCD-EFGH-IJKL-123456789012
      index: sfx
      source: sfx
      eventsIndex: traces
      eventsSource: traces
      skipTLSVerify: true

  logging:
    level: info
    format: text

  globalDimensions:
    kubernetes_cluster: dev-cluster

  observers:
    - type: k8s-api
      discoverAllPods: false
      discoverNodes: false

  monitors:
    - type: cpu
    - type: filesystems
      hostFSPath: /hostfs
    - type: disk-io
    - type: net-io
    - type: load
    - type: memory
    - type: host-metadata
    - type: processlist
    - type: vmem


    - type: kubelet-metrics
      kubeletAPI:
        authType: serviceAccount
        skipVerify: true
      usePodsEndpoint: true

    # Collects k8s cluster-level metrics
    - type: kubernetes-cluster

    - type: docker-container-stats
      dockerURL: unix:///var/run/docker.sock
      excludedImages:
        - '*pause-amd64*'
        - 'k8s.gcr.io/pause*'
      labelsToDimensions:
        io.kubernetes.container.name: container_spec_name
        io.kubernetes.pod.name: kubernetes_pod_name
        io.kubernetes.pod.uid: kubernetes_pod_uid
        io.kubernetes.pod.namespace: kubernetes_namespace
    - type: kube-controller-manager
      discoveryRule: kubernetes_pod_name =~ "kube-controller-manager" && target == "pod"
      extraDimensions:
        metric_source: kube-controller-manager
      port: 10252

    - type: prometheus-exporter
      discoveryRule: kubernetes_pod_name =~ "prometheus-prometheus" && target == "pod"
      extraDimensions:
        metric_source: prometheus
      host: prometheus
      metricPath: /federate?match[]=%7Bendpoint%3D%22operations%22%7D
      port: 9090

    - type: trace-forwarder
      extraSpanTags:
        environment: hyperledger-demo
      listenAddress: 0.0.0.0:9080



  collectd:
    readThreads: 5
    writeQueueLimitHigh: 500000
    writeQueueLimitLow: 400000
    timeout: 40
    logLevel: info

  metricsToExclude:
    # The StackDriver metadata-agent pod on GKE restarts every few minutes so
    # ignore its containers
    - dimensions:
        container_spec_name: metadata-agent